version: "3"

vars:
  IGNORE_FONTS: --ignore-embedded-fonts --ignore-system-fonts
  VARIABLE_FONTS: --font-path assets/fonts/variable
  STATIC_FONTS: --font-path assets/fonts/static
  CARGO_RUN_COMPILE_VARIABLE: cargo run -- compile {{.IGNORE_FONTS}} {{.VARIABLE_FONTS}}
  CARGO_RUN_COMPILE_STATIC: cargo run -- compile {{.IGNORE_FONTS}} {{.STATIC_FONTS}}

tasks:
  bench:
    cmds:
      - hyperfine -w 3 -r 5 "typst compile {{.IGNORE_FONTS}} {{.STATIC_FONTS}} local-testing/test.typ local-testing/out/test-stable.pdf"
      - hyperfine -w 3 -r 5 "C:/Users/Jassiel/.cargo/target/release/typst compile {{.IGNORE_FONTS}} {{.VARIABLE_FONTS}} local-testing/test.typ local-testing/out/test-nightly.pdf"
  exhaustive:
    cmds:
      - "{{.CARGO_RUN_COMPILE_VARIABLE}} local-testing/exhaustive.typ local-testing/out/exhaustive.pdf"
      - typst compile {{.IGNORE_FONTS}} {{.STATIC_FONTS}} local-testing/exhaustive.typ local-testing/out/exhaustive-static.pdf
  weight:
    cmds:
      - "{{.CARGO_RUN_COMPILE_VARIABLE}} tests/variable-fonts/weight.typ"
  italic:
    cmds:
      - "{{.CARGO_RUN_COMPILE_VARIABLE}} tests/variable-fonts/italic.typ"
